### ISSUE TITLE
Bluetooth mac address seems random

### ISSUE THREAD

**Issue by hansmbakker** [getsenic/nuimo-emulator-ios#1]
Every time I switch on and off Nuimo (by switching Bluetooth on/off) the bluetooth mac address of the emulator seems to change.

Is this done on purpose?

**Comment by larsblumberg** [comment]
This is how the Android OS handles the peripheral mode. It assigns a new MAC address every time a peripheral is created. This is probably due to the fact that some Android devices allow to create multiple BLE peripherals at the same time. Creating new MAC addresses also has the advantage the centrals that connect to "new" peripherals can't use the cached data (e.g. BLE services) about the peripheral.

**Comment by larsblumberg** [comment]
This behavior is handled by the iOS operating system. I can't explain why it does so but it probably has some advantages.
